<div class="field cnpj">
    <label class="label" for="cnpj"><span><?php /* @escapeNotVerified */ echo __('CNPJ') ?></span></label>
    <div class="control">
        <input type="text" id="cnpj" name="cnpj" value="<?php echo $block->escapeHtml($block->getCustomer()->getCustomAttribute('cnpj')->getValue()) ?>" title="<?php /* @escapeNotVerified */ echo __('CNPJ') ?>" class="input-text" data-validate="{required:false}" autocomplete="off" />
    </div>
</div>