<div class="field cpf required">
    <label class="label" for="cpf"><span><?php /* @escapeNotVerified */ echo __('CPF') ?></span></label>
    <div class="control">
        <input type="text" id="cpf" name="cpf" value="<?php echo $block->escapeHtml($block->getCustomer()->getCustomAttribute('cpf')->getValue()) ?>" title="<?php /* @escapeNotVerified */ echo __('CPF') ?>" class="input-text" data-validate="{required:true}" autocomplete="off" />
    </div>
</div>